-- Transaction 

BEGIN TRANS;

UPDATE account
SET Balance = Balance - 100
WHERE Id = 1;

UPDATE account
SET Balance = Balance + 100
WHERE Id = 2;

COMMIT TRANS;

-- Isolation Level 
-- READ UNCOMMITTED

SET ISOLATION LEVEL READ UNCOMMITTED;
SELECT * FROM account; -- Dirty Page    
FROM Porduction.Profuct with(nolock); -- Lock free read

-- READ COMMITED

SET ISOLATION LEVEL READ COMMITTED
 
-- REPEATABLE READ

BEGIN TRANS
SET ISOLATION LEVEL REPEATABLE READ

SELECT * 
FROM Porduction.Product
WHERE Productid = 2

UPDATE  Porduction.Product
SET unitprice += 1.00

COMMIT TRANS

-- SERIALIZABLE

SET ISOLATION LEVEL SERIALIZABLE

-- SNAPSHOT 

ALTER DATABASE dbname SET ALLOW_SNAPSHOT_ISOLATION ON 
SET ISOLATION LEVEL SNAPSHOT

BEGIN TRANS 

UPDATE Porduction.Product
SET unitprice += 1
WHERE Productid = 2

SELECT Productid

COMMIT TRANS

-- READ COMMITED SNAPSHOT 

ALTER DATABASE dbname SET READ_COMMITED_SNAPSHOT ON